### PR TITLE
fix: adjusting repo url

### PR DESCRIPTION
**Pull request by william-keller**
## Testing

-   [x ] I have read the **README** document
-   [ x] I have read the **CONTRIBUTING** document
-   [ x] My code follows the code style of this project
-   [ x] I have added tests to cover my changes
-   [ x] A short description of the change has been added to the changelog using the script `npm run newChange`

## License

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rbbarad — APPROVED** [review]

**Comment by rbbarad** [comment]
Thanks for the contribution!

**Comment by stevebanik** [comment]
When will this be merged?

**Pull request merged**
